export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  recovery: "/recovery",
  recoveryRequest: "/recovery/request",
  vault: "/vault",
  account: "/account",
  admin: "/admin",
  adminAuth: "/admin/auth",
  adminLogin: "/admin/login",
  adminUsers: "/admin/users",
  adminLogs: "/admin/logs",
  adminConfigKdf: "/admin/config/kdf",
  adminConfigSession: "/admin/config/session",
  adminHealth: "/admin/health",
};
